final  googleFontList = [
  {'name': 'ABeeZee', 'group': 'system'},
  {'name': 'Abel', 'group': 'system'},
  {'name': 'Abhaya Libre', 'group': 'system'},
  {'name': 'Abril Fatface', 'group': 'system'},
  {'name': 'Aclonica', 'group': 'system'},
  {'name': 'Acme', 'group': 'system'},
  {'name': 'Actor', 'group': 'system'},
  {'name': 'Adamina', 'group': 'system'},
  {'name': 'Advent Pro', 'group': 'system'},
  {'name': 'Aguafina Script', 'group': 'system'},
  {'name': 'Akaya Telivigala', 'group': 'system'},
  {'name': 'Akronim', 'group': 'system'},
  {'name': 'Aladin', 'group': 'system'},
  {'name': 'Alata', 'group': 'system'},
  {'name': 'Alatsi', 'group': 'system'},
  {'name': 'Aldrich', 'group': 'system'},
  {'name': 'Alef', 'group': 'system'},
  {'name': 'Alegreya', 'group': 'system'},
  {'name': 'Alegreya Sans', 'group': 'system'},
  {'name': 'Alegreya Sans SC', 'group': 'system'},
  {'name': 'Aleo', 'group': 'system'},
  {'name': 'Alex Brush', 'group': 'system'},
  {'name': 'Alfa Slab One', 'group': 'system'},
  {'name': 'Alice', 'group': 'system'},
  {'name': 'Alike', 'group': 'system'},
  {'name': 'Alike Angular', 'group': 'system'},
  {'name': 'Allan', 'group': 'system'},
  {'name': 'Allerta', 'group': 'system'},
  {'name': 'Allerta Stencil', 'group': 'system'},
  {'name': 'Allison', 'group': 'system'},
  {'name': 'Allura', 'group': 'system'},
  {'name': 'Almarai', 'group': 'system'},
  {'name': 'Almendra', 'group': 'system'},
  {'name': 'Almendra Display', 'group': 'system'},
  {'name': 'Almendra SC', 'group': 'system'},
  {'name': 'Alumni Sans', 'group': 'system'},
  {'name': 'Amarante', 'group': 'system'},
  {'name': 'Amaranth', 'group': 'system'},
  {'name': 'Amatic SC', 'group': 'system'},
  {'name': 'Amethysta', 'group': 'system'},
  {'name': 'Amiko', 'group': 'system'},
  {'name': 'Amiri', 'group': 'system'},
  {'name': 'Amita', 'group': 'system'},
  {'name': 'Anaheim', 'group': 'system'},
  {'name': 'Andada Pro', 'group': 'system'},
  {'name': 'Andika', 'group': 'system'},
  {'name': 'Andika New Basic', 'group': 'system'},
  {'name': 'Annie Use Your Telescope', 'group': 'system'},
  {'name': 'Anonymous Pro', 'group': 'system'},
  {'name': 'Antic', 'group': 'system'},
  {'name': 'Antic Didone', 'group': 'system'},
  {'name': 'Antic Slab', 'group': 'system'},
  {'name': 'Anton', 'group': 'system'},
  {'name': 'Arapey', 'group': 'system'},
  {'name': 'Arbutus', 'group': 'system'},
  {'name': 'Arbutus Slab', 'group': 'system'},
  {'name': 'Architects Daughter', 'group': 'system'},
  {'name': 'Archivo', 'group': 'system'},
  {'name': 'Archivo Black', 'group': 'system'},
  {'name': 'Archivo Narrow', 'group': 'system'},
  {'name': 'Are You Serious', 'group': 'system'},
  {'name': 'Aref Ruqaa', 'group': 'system'},
  {'name': 'Arima Madurai', 'group': 'system'},
  {'name': 'Arimo', 'group': 'system'},
  {'name': 'Arizonia', 'group': 'system'},
  {'name': 'Armata', 'group': 'system'},
  {'name': 'Arsenal', 'group': 'system'},
  {'name': 'Artifika', 'group': 'system'},
  {'name': 'Arvo', 'group': 'system'},
  {'name': 'Arya', 'group': 'system'},
  {'name': 'Asap', 'group': 'system'},
  {'name': 'Asar', 'group': 'system'},
  {'name': 'Asset', 'group': 'system'},
  {'name': 'Assistant', 'group': 'system'},
  {'name': 'Astloch', 'group': 'system'},
  {'name': 'Asul', 'group': 'system'},
  {'name': 'Athiti', 'group': 'system'},
  {'name': 'Atkinson Hyperlegible', 'group': 'system'},
  {'name': 'Atma', 'group': 'system'},
  {'name': 'Atomic Age', 'group': 'system'},
  {'name': 'Aubrey', 'group': 'system'},
  {'name': 'Audiowide', 'group': 'system'},
  {'name': 'Autour One', 'group': 'system'},
  {'name': 'Average', 'group': 'system'},
  {'name': 'Average Sans', 'group': 'system'},
  {'name': 'Averia Gruesa Libre', 'group': 'system'},
  {'name': 'Averia Libre', 'group': 'system'},
  {'name': 'Averia Sans Libre', 'group': 'system'},
  {'name': 'Averia Serif Libre', 'group': 'system'},
  {'name': 'Azeret Mono', 'group': 'system'},
  {'name': 'B612', 'group': 'system'},
  {'name': 'B612 Mono', 'group': 'system'},
  {'name': 'Bad Script', 'group': 'system'},
  {'name': 'Bahiana', 'group': 'system'},
  {'name': 'Bahianita', 'group': 'system'},
  {'name': 'Bai Jamjuree', 'group': 'system'},
  {'name': 'Bakbak One', 'group': 'system'},
  {'name': 'Baloo 2', 'group': 'system'},
  {'name': 'Baloo Bhai 2', 'group': 'system'},
  {'name': 'Baloo Bhaijaan 2', 'group': 'system'},
  {'name': 'Baloo Bhaina 2', 'group': 'system'},
  {'name': 'Baloo Chettan 2', 'group': 'system'},
  {'name': 'Baloo Da 2', 'group': 'system'},
  {'name': 'Baloo Paaji 2', 'group': 'system'},
  {'name': 'Baloo Tamma 2', 'group': 'system'},
  {'name': 'Baloo Tammudu 2', 'group': 'system'},
  {'name': 'Baloo Thambi 2', 'group': 'system'},
  {'name': 'Balsamiq Sans', 'group': 'system'},
  {'name': 'Balthazar', 'group': 'system'},
  {'name': 'Bangers', 'group': 'system'},
  {'name': 'Barlow', 'group': 'system'},
  {'name': 'Barlow Condensed', 'group': 'system'},
  {'name': 'Barlow Semi Condensed', 'group': 'system'},
  {'name': 'Barriecito', 'group': 'system'},
  {'name': 'Barrio', 'group': 'system'},
  {'name': 'Basic', 'group': 'system'},
  {'name': 'Baskervville', 'group': 'system'},
  {'name': 'Baumans', 'group': 'system'},
  {'name': 'Be Vietnam Pro', 'group': 'system'},
  {'name': 'Bebas Neue', 'group': 'system'},
  {'name': 'Belgrano', 'group': 'system'},
  {'name': 'Bellefair', 'group': 'system'},
  {'name': 'Belleza', 'group': 'system'},
  {'name': 'Bellota', 'group': 'system'},
  {'name': 'Bellota Text', 'group': 'system'},
  {'name': 'Bentham', 'group': 'system'},
  {'name': 'Berkshire Swash', 'group': 'system'},
  {'name': 'Besley', 'group': 'system'},
  {'name': 'Beth Ellen', 'group': 'system'},
  {'name': 'Bevan', 'group': 'system'},
  {'name': 'Big Shoulders Display', 'group': 'system'},
  {'name': 'Big Shoulders Inline Display', 'group': 'system'},
  {'name': 'Big Shoulders Inline Text', 'group': 'system'},
  {'name': 'Big Shoulders Stencil Display', 'group': 'system'},
  {'name': 'Big Shoulders Stencil Text', 'group': 'system'},
  {'name': 'Big Shoulders Text', 'group': 'system'},
  {'name': 'Bigelow Rules', 'group': 'system'},
  {'name': 'Bigshot One', 'group': 'system'},
  {'name': 'Bilbo', 'group': 'system'},
  {'name': 'Bilbo Swash Caps', 'group': 'system'},
  {'name': 'BioRhyme', 'group': 'system'},
  {'name': 'BioRhyme Expanded', 'group': 'system'},
  {'name': 'Birthstone', 'group': 'system'},
  {'name': 'Birthstone Bounce', 'group': 'system'},
  {'name': 'Biryani', 'group': 'system'},
  {'name': 'Bitter', 'group': 'system'},
  {'name': 'Black And White Picture', 'group': 'system'},
  {'name': 'Black Han Sans', 'group': 'system'},
  {'name': 'Black Ops One', 'group': 'system'},
  {'name': 'Blinker', 'group': 'system'},
  {'name': 'Bona Nova', 'group': 'system'},
  {'name': 'Bonbon', 'group': 'system'},
  {'name': 'Bonheur Royale', 'group': 'system'},
  {'name': 'Boogaloo', 'group': 'system'},
  {'name': 'Bowlby One', 'group': 'system'},
  {'name': 'Bowlby One SC', 'group': 'system'},
  {'name': 'Brawler', 'group': 'system'},
  {'name': 'Bree Serif', 'group': 'system'},
  {'name': 'Brygada 1918', 'group': 'system'},
  {'name': 'Bubblegum Sans', 'group': 'system'},
  {'name': 'Bubbler One', 'group': 'system'},
  {'name': 'Buda', 'group': 'system'},
  {'name': 'Buenard', 'group': 'system'},
  {'name': 'Bungee', 'group': 'system'},
  {'name': 'Bungee Hairline', 'group': 'system'},
  {'name': 'Bungee Inline', 'group': 'system'},
  {'name': 'Bungee Outline', 'group': 'system'},
  {'name': 'Bungee Shade', 'group': 'system'},
  {'name': 'Butcherman', 'group': 'system'},
  {'name': 'Butterfly Kids', 'group': 'system'},
  {'name': 'Cabin', 'group': 'system'},
  {'name': 'Cabin Condensed', 'group': 'system'},
  {'name': 'Cabin Sketch', 'group': 'system'},
  {'name': 'Caesar Dressing', 'group': 'system'},
  {'name': 'Cagliostro', 'group': 'system'},
  {'name': 'Cairo', 'group': 'system'},
  {'name': 'Caladea', 'group': 'system'},
  {'name': 'Calistoga', 'group': 'system'},
  {'name': 'Calligraffitti', 'group': 'system'},
  {'name': 'Cambay', 'group': 'system'},
  {'name': 'Cambo', 'group': 'system'},
  {'name': 'Candal', 'group': 'system'},
  {'name': 'Cantarell', 'group': 'system'},
  {'name': 'Cantata One', 'group': 'system'},
  {'name': 'Cantora One', 'group': 'system'},
  {'name': 'Capriola', 'group': 'system'},
  {'name': 'Caramel', 'group': 'system'},
  {'name': 'Carattere', 'group': 'system'},
  {'name': 'Cardo', 'group': 'system'},
  {'name': 'Carme', 'group': 'system'},
  {'name': 'Carrois Gothic', 'group': 'system'},
  {'name': 'Carrois Gothic SC', 'group': 'system'},
  {'name': 'Carter One', 'group': 'system'},
  {'name': 'Castoro', 'group': 'system'},
  {'name': 'Catamaran', 'group': 'system'},
  {'name': 'Caudex', 'group': 'system'},
  {'name': 'Caveat', 'group': 'system'},
  {'name': 'Caveat Brush', 'group': 'system'},
  {'name': 'Cedarville Cursive', 'group': 'system'},
  {'name': 'Ceviche One', 'group': 'system'},
  {'name': 'Chakra Petch', 'group': 'system'},
  {'name': 'Changa', 'group': 'system'},
  {'name': 'Changa One', 'group': 'system'},
  {'name': 'Chango', 'group': 'system'},
  {'name': 'Charm', 'group': 'system'},
  {'name': 'Charmonman', 'group': 'system'},
  {'name': 'Chathura', 'group': 'system'},
  {'name': 'Chau Philomene One', 'group': 'system'},
  {'name': 'Chela One', 'group': 'system'},
  {'name': 'Chelsea Market', 'group': 'system'},
  {'name': 'Cherish', 'group': 'system'},
  {'name': 'Cherry Cream Soda', 'group': 'system'},
  {'name': 'Cherry Swash', 'group': 'system'},
  {'name': 'Chewy', 'group': 'system'},
  {'name': 'Chicle', 'group': 'system'},
  {'name': 'Chilanka', 'group': 'system'},
  {'name': 'Chivo', 'group': 'system'},
  {'name': 'Chonburi', 'group': 'system'},
  {'name': 'Cinzel', 'group': 'system'},
  {'name': 'Cinzel Decorative', 'group': 'system'},
  {'name': 'Clicker Script', 'group': 'system'},
  {'name': 'Coda', 'group': 'system'},
  {'name': 'Coda Caption', 'group': 'system'},
  {'name': 'Codystar', 'group': 'system'},
  {'name': 'Coiny', 'group': 'system'},
  {'name': 'Combo', 'group': 'system'},
  {'name': 'Comfortaa', 'group': 'system'},
  {'name': 'Comforter', 'group': 'system'},
  {'name': 'Comforter Brush', 'group': 'system'},
  {'name': 'Comic Neue', 'group': 'system'},
  {'name': 'Coming Soon', 'group': 'system'},
  {'name': 'Commissioner', 'group': 'system'},
  {'name': 'Concert One', 'group': 'system'},
  {'name': 'Condiment', 'group': 'system'},
  {'name': 'Contrail One', 'group': 'system'},
  {'name': 'Convergence', 'group': 'system'},
  {'name': 'Cookie', 'group': 'system'},
  {'name': 'Copse', 'group': 'system'},
  {'name': 'Corben', 'group': 'system'},
  {'name': 'Corinthia', 'group': 'system'},
  {'name': 'Cormorant', 'group': 'system'},
  {'name': 'Cormorant Garamond', 'group': 'system'},
  {'name': 'Cormorant Infant', 'group': 'system'},
  {'name': 'Cormorant SC', 'group': 'system'},
  {'name': 'Cormorant Unicase', 'group': 'system'},
  {'name': 'Cormorant Upright', 'group': 'system'},
  {'name': 'Courgette', 'group': 'system'},
  {'name': 'Courier Prime', 'group': 'system'},
  {'name': 'Cousine', 'group': 'system'},
  {'name': 'Coustard', 'group': 'system'},
  {'name': 'Covered By Your Grace', 'group': 'system'},
  {'name': 'Crafty Girls', 'group': 'system'},
  {'name': 'Creepster', 'group': 'system'},
  {'name': 'Crete Round', 'group': 'system'},
  {'name': 'Crimson Pro', 'group': 'system'},
  {'name': 'Croissant One', 'group': 'system'},
  {'name': 'Crushed', 'group': 'system'},
  {'name': 'Cuprum', 'group': 'system'},
  {'name': 'Cute Font', 'group': 'system'},
  {'name': 'Cutive', 'group': 'system'},
  {'name': 'Cutive Mono', 'group': 'system'},
  {'name': 'DM Mono', 'group': 'system'},
  {'name': 'DM Sans', 'group': 'system'},
  {'name': 'DM Serif Display', 'group': 'system'},
  {'name': 'DM Serif Text', 'group': 'system'},
  {'name': 'Damion', 'group': 'system'},
  {'name': 'Dancing Script', 'group': 'system'},
  {'name': 'Darker Grotesque', 'group': 'system'},
  {'name': 'David Libre', 'group': 'system'},
  {'name': 'Dawning of a New Day', 'group': 'system'},
  {'name': 'Days One', 'group': 'system'},
  {'name': 'Dekko', 'group': 'system'},
  {'name': 'Dela Gothic One', 'group': 'system'},
  {'name': 'Delius', 'group': 'system'},
  {'name': 'Delius Swash Caps', 'group': 'system'},
  {'name': 'Delius Unicase', 'group': 'system'},
  {'name': 'Della Respira', 'group': 'system'},
  {'name': 'Denk One', 'group': 'system'},
  {'name': 'Devonshire', 'group': 'system'},
  {'name': 'Dhurjati', 'group': 'system'},
  {'name': 'Didact Gothic', 'group': 'system'},
  {'name': 'Diplomata', 'group': 'system'},
  {'name': 'Diplomata SC', 'group': 'system'},
  {'name': 'Do Hyeon', 'group': 'system'},
  {'name': 'Dokdo', 'group': 'system'},
  {'name': 'Domine', 'group': 'system'},
  {'name': 'Donegal One', 'group': 'system'},
  {'name': 'Dongle', 'group': 'system'},
  {'name': 'Doppio One', 'group': 'system'},
  {'name': 'Dorsa', 'group': 'system'},
  {'name': 'Dosis', 'group': 'system'},
  {'name': 'DotGothic16', 'group': 'system'},
  {'name': 'Dr Sugiyama', 'group': 'system'},
  {'name': 'Duru Sans', 'group': 'system'},
  {'name': 'Dynalight', 'group': 'system'},
  {'name': 'EB Garamond', 'group': 'system'},
  {'name': 'Eagle Lake', 'group': 'system'},
  {'name': 'East Sea Dokdo', 'group': 'system'},
  {'name': 'Eater', 'group': 'system'},
  {'name': 'Economica', 'group': 'system'},
  {'name': 'Eczar', 'group': 'system'},
  {'name': 'El Messiri', 'group': 'system'},
  {'name': 'Electrolize', 'group': 'system'},
  {'name': 'Elsie', 'group': 'system'},
  {'name': 'Elsie Swash Caps', 'group': 'system'},
  {'name': 'Emblema One', 'group': 'system'},
  {'name': 'Emilys Candy', 'group': 'system'},
  {'name': 'Encode Sans', 'group': 'system'},
  {'name': 'Encode Sans Condensed', 'group': 'system'},
  {'name': 'Encode Sans Expanded', 'group': 'system'},
  {'name': 'Encode Sans SC', 'group': 'system'},
  {'name': 'Encode Sans Semi Condensed', 'group': 'system'},
  {'name': 'Encode Sans Semi Expanded', 'group': 'system'},
  {'name': 'Engagement', 'group': 'system'},
  {'name': 'Englebert', 'group': 'system'},
  {'name': 'Enriqueta', 'group': 'system'},
  {'name': 'Ephesis', 'group': 'system'},
  {'name': 'Epilogue', 'group': 'system'},
  {'name': 'Erica One', 'group': 'system'},
  {'name': 'Esteban', 'group': 'system'},
  {'name': 'Estonia', 'group': 'system'},
  {'name': 'Euphoria Script', 'group': 'system'},
  {'name': 'Ewert', 'group': 'system'},
  {'name': 'Exo', 'group': 'system'},
  {'name': 'Exo 2', 'group': 'system'},
  {'name': 'Expletus Sans', 'group': 'system'},
  {'name': 'Explora', 'group': 'system'},
  {'name': 'Fahkwang', 'group': 'system'},
  {'name': 'Fanwood Text', 'group': 'system'},
  {'name': 'Farro', 'group': 'system'},
  {'name': 'Farsan', 'group': 'system'},
  {'name': 'Fascinate', 'group': 'system'},
  {'name': 'Fascinate Inline', 'group': 'system'},
  {'name': 'Faster One', 'group': 'system'},
  {'name': 'Fauna One', 'group': 'system'},
  {'name': 'Faustina', 'group': 'system'},
  {'name': 'Federant', 'group': 'system'},
  {'name': 'Federo', 'group': 'system'},
  {'name': 'Felipa', 'group': 'system'},
  {'name': 'Fenix', 'group': 'system'},
  {'name': 'Festive', 'group': 'system'},
  {'name': 'Finger Paint', 'group': 'system'},
  {'name': 'Fira Code', 'group': 'system'},
  {'name': 'Fira Mono', 'group': 'system'},
  {'name': 'Fira Sans', 'group': 'system'},
  {'name': 'Fira Sans Condensed', 'group': 'system'},
  {'name': 'Fira Sans Extra Condensed', 'group': 'system'},
  {'name': 'Fjalla One', 'group': 'system'},
  {'name': 'Fjord One', 'group': 'system'},
  {'name': 'Flamenco', 'group': 'system'},
  {'name': 'Flavors', 'group': 'system'},
  {'name': 'Fleur De Leah', 'group': 'system'},
  {'name': 'Flow Block', 'group': 'system'},
  {'name': 'Flow Circular', 'group': 'system'},
  {'name': 'Flow Rounded', 'group': 'system'},
  {'name': 'Fondamento', 'group': 'system'},
  {'name': 'Fontdiner Swanky', 'group': 'system'},
  {'name': 'Forum', 'group': 'system'},
  {'name': 'Francois One', 'group': 'system'},
  {'name': 'Frank Ruhl Libre', 'group': 'system'},
  {'name': 'Fraunces', 'group': 'system'},
  {'name': 'Freckle Face', 'group': 'system'},
  {'name': 'Fredericka the Great', 'group': 'system'},
  {'name': 'Fredoka One', 'group': 'system'},
  {'name': 'Fresca', 'group': 'system'},
  {'name': 'Frijole', 'group': 'system'},
  {'name': 'Fruktur', 'group': 'system'},
  {'name': 'Fugaz One', 'group': 'system'},
  {'name': 'Fuggles', 'group': 'system'},
  {'name': 'Fuzzy Bubbles', 'group': 'system'},
  {'name': 'GFS Didot', 'group': 'system'},
  {'name': 'GFS Neohellenic', 'group': 'system'},
  {'name': 'Gabriela', 'group': 'system'},
  {'name': 'Gaegu', 'group': 'system'},
  {'name': 'Gafata', 'group': 'system'},
  {'name': 'Galada', 'group': 'system'},
  {'name': 'Galdeano', 'group': 'system'},
  {'name': 'Galindo', 'group': 'system'},
  {'name': 'Gamja Flower', 'group': 'system'},
  {'name': 'Gayathri', 'group': 'system'},
  {'name': 'Gelasio', 'group': 'system'},
  {'name': 'Gemunu Libre', 'group': 'system'},
  {'name': 'Genos', 'group': 'system'},
  {'name': 'Gentium Basic', 'group': 'system'},
  {'name': 'Gentium Book Basic', 'group': 'system'},
  {'name': 'Geo', 'group': 'system'},
  {'name': 'Georama', 'group': 'system'},
  {'name': 'Geostar', 'group': 'system'},
  {'name': 'Geostar Fill', 'group': 'system'},
  {'name': 'Germania One', 'group': 'system'},
  {'name': 'Gideon Roman', 'group': 'system'},
  {'name': 'Gidugu', 'group': 'system'},
  {'name': 'Gilda Display', 'group': 'system'},
  {'name': 'Girassol', 'group': 'system'},
  {'name': 'Give You Glory', 'group': 'system'},
  {'name': 'Glass Antiqua', 'group': 'system'},
  {'name': 'Glegoo', 'group': 'system'},
  {'name': 'Gloria Hallelujah', 'group': 'system'},
  {'name': 'Glory', 'group': 'system'},
  {'name': 'Gluten', 'group': 'system'},
  {'name': 'Goblin One', 'group': 'system'},
  {'name': 'Gochi Hand', 'group': 'system'},
  {'name': 'Goldman', 'group': 'system'},
  {'name': 'Gorditas', 'group': 'system'},
  {'name': 'Gothic A1', 'group': 'system'},
  {'name': 'Gotu', 'group': 'system'},
  {'name': 'Goudy Bookletter 1911', 'group': 'system'},
  {'name': 'Gowun Batang', 'group': 'system'},
  {'name': 'Gowun Dodum', 'group': 'system'},
  {'name': 'Graduate', 'group': 'system'},
  {'name': 'Grand Hotel', 'group': 'system'},
  {'name': 'Grandstander', 'group': 'system'},
  {'name': 'Gravitas One', 'group': 'system'},
  {'name': 'Great Vibes', 'group': 'system'},
  {'name': 'Grechen Fuemen', 'group': 'system'},
  {'name': 'Grenze', 'group': 'system'},
  {'name': 'Grenze Gotisch', 'group': 'system'},
  {'name': 'Grey Qo', 'group': 'system'},
  {'name': 'Griffy', 'group': 'system'},
  {'name': 'Gruppo', 'group': 'system'},
  {'name': 'Gudea', 'group': 'system'},
  {'name': 'Gugi', 'group': 'system'},
  {'name': 'Gupter', 'group': 'system'},
  {'name': 'Gurajada', 'group': 'system'},
  {'name': 'Gwendolyn', 'group': 'system'},
  {'name': 'Habibi', 'group': 'system'},
  {'name': 'Hachi Maru Pop', 'group': 'system'},
  {'name': 'Hahmlet', 'group': 'system'},
  {'name': 'Halant', 'group': 'system'},
  {'name': 'Hammersmith One', 'group': 'system'},
  {'name': 'Hanalei', 'group': 'system'},
  {'name': 'Hanalei Fill', 'group': 'system'},
  {'name': 'Handlee', 'group': 'system'},
  {'name': 'Happy Monkey', 'group': 'system'},
  {'name': 'Harmattan', 'group': 'system'},
  {'name': 'Headland One', 'group': 'system'},
  {'name': 'Heebo', 'group': 'system'},
  {'name': 'Henny Penny', 'group': 'system'},
  {'name': 'Hepta Slab', 'group': 'system'},
  {'name': 'Herr Von Muellerhoff', 'group': 'system'},
  {'name': 'Hi Melody', 'group': 'system'},
  {'name': 'Hina Mincho', 'group': 'system'},
  {'name': 'Hind', 'group': 'system'},
  {'name': 'Hind Guntur', 'group': 'system'},
  {'name': 'Hind Madurai', 'group': 'system'},
  {'name': 'Hind Siliguri', 'group': 'system'},
  {'name': 'Hind Vadodara', 'group': 'system'},
  {'name': 'Holtwood One SC', 'group': 'system'},
  {'name': 'Homemade Apple', 'group': 'system'},
  {'name': 'Homenaje', 'group': 'system'},
  {'name': 'Hurricane', 'group': 'system'},
  {'name': 'IBM Plex Mono', 'group': 'system'},
  {'name': 'IBM Plex Sans', 'group': 'system'},
  {'name': 'IBM Plex Sans Arabic', 'group': 'system'},
  {'name': 'IBM Plex Sans Condensed', 'group': 'system'},
  {'name': 'IBM Plex Sans Devanagari', 'group': 'system'},
  {'name': 'IBM Plex Sans Hebrew', 'group': 'system'},
  {'name': 'IBM Plex Sans KR', 'group': 'system'},
  {'name': 'IBM Plex Sans Thai', 'group': 'system'},
  {'name': 'IBM Plex Sans Thai Looped', 'group': 'system'},
  {'name': 'IBM Plex Serif', 'group': 'system'},
  {'name': 'IM Fell DW Pica', 'group': 'system'},
  {'name': 'IM Fell DW Pica SC', 'group': 'system'},
  {'name': 'IM Fell Double Pica', 'group': 'system'},
  {'name': 'IM Fell Double Pica SC', 'group': 'system'},
  {'name': 'IM Fell English', 'group': 'system'},
  {'name': 'IM Fell English SC', 'group': 'system'},
  {'name': 'IM Fell French Canon', 'group': 'system'},
  {'name': 'IM Fell French Canon SC', 'group': 'system'},
  {'name': 'IM Fell Great Primer', 'group': 'system'},
  {'name': 'IM Fell Great Primer SC', 'group': 'system'},
  {'name': 'Ibarra Real Nova', 'group': 'system'},
  {'name': 'Iceberg', 'group': 'system'},
  {'name': 'Iceland', 'group': 'system'},
  {'name': 'Imprima', 'group': 'system'},
  {'name': 'Inconsolata', 'group': 'system'},
  {'name': 'Inder', 'group': 'system'},
  {'name': 'Indie Flower', 'group': 'system'},
  {'name': 'Inika', 'group': 'system'},
  {'name': 'Inknut Antiqua', 'group': 'system'},
  {'name': 'Inria Sans', 'group': 'system'},
  {'name': 'Inria Serif', 'group': 'system'},
  {'name': 'Inter', 'group': 'system'},
  {'name': 'Irish Grover', 'group': 'system'},
  {'name': 'Istok Web', 'group': 'system'},
  {'name': 'Italiana', 'group': 'system'},
  {'name': 'Italianno', 'group': 'system'},
  {'name': 'Itim', 'group': 'system'},
  {'name': 'Jacques Francois', 'group': 'system'},
  {'name': 'Jacques Francois Shadow', 'group': 'system'},
  {'name': 'Jaldi', 'group': 'system'},
  {'name': 'JetBrains Mono', 'group': 'system'},
  {'name': 'Jim Nightshade', 'group': 'system'},
  {'name': 'Jockey One', 'group': 'system'},
  {'name': 'Jolly Lodger', 'group': 'system'},
  {'name': 'Jomhuria', 'group': 'system'},
  {'name': 'Jomolhari', 'group': 'system'},
  {'name': 'Josefin Sans', 'group': 'system'},
  {'name': 'Josefin Slab', 'group': 'system'},
  {'name': 'Jost', 'group': 'system'},
  {'name': 'Joti One', 'group': 'system'},
  {'name': 'Jua', 'group': 'system'},
  {'name': 'Judson', 'group': 'system'},
  {'name': 'Julee', 'group': 'system'},
  {'name': 'Julius Sans One', 'group': 'system'},
  {'name': 'Junge', 'group': 'system'},
  {'name': 'Jura', 'group': 'system'},
  {'name': 'Just Another Hand', 'group': 'system'},
  {'name': 'Just Me Again Down Here', 'group': 'system'},
  {'name': 'K2D', 'group': 'system'},
  {'name': 'Kadwa', 'group': 'system'},
  {'name': 'Kaisei Decol', 'group': 'system'},
  {'name': 'Kaisei HarunoUmi', 'group': 'system'},
  {'name': 'Kaisei Opti', 'group': 'system'},
  {'name': 'Kaisei Tokumin', 'group': 'system'},
  {'name': 'Kalam', 'group': 'system'},
  {'name': 'Kameron', 'group': 'system'},
  {'name': 'Kanit', 'group': 'system'},
  {'name': 'Kantumruy', 'group': 'system'},
  {'name': 'Karla', 'group': 'system'},
  {'name': 'Karma', 'group': 'system'},
  {'name': 'Katibeh', 'group': 'system'},
  {'name': 'Kaushan Script', 'group': 'system'},
  {'name': 'Kavivanar', 'group': 'system'},
  {'name': 'Kavoon', 'group': 'system'},
  {'name': 'Kdam Thmor', 'group': 'system'},
  {'name': 'Keania One', 'group': 'system'},
  {'name': 'Kelly Slab', 'group': 'system'},
  {'name': 'Kenia', 'group': 'system'},
  {'name': 'Khand', 'group': 'system'},
  {'name': 'Khula', 'group': 'system'},
  {'name': 'Kings', 'group': 'system'},
  {'name': 'Kirang Haerang', 'group': 'system'},
  {'name': 'Kite One', 'group': 'system'},
  {'name': 'Klee One', 'group': 'system'},
  {'name': 'Knewave', 'group': 'system'},
  {'name': 'KoHo', 'group': 'system'},
  {'name': 'Kodchasan', 'group': 'system'},
  {'name': 'Koh Santepheap', 'group': 'system'},
  {'name': 'Kosugi', 'group': 'system'},
  {'name': 'Kosugi Maru', 'group': 'system'},
  {'name': 'Kotta One', 'group': 'system'},
  {'name': 'Kranky', 'group': 'system'},
  {'name': 'Kreon', 'group': 'system'},
  {'name': 'Kristi', 'group': 'system'},
  {'name': 'Krona One', 'group': 'system'},
  {'name': 'Krub', 'group': 'system'},
  {'name': 'Kufam', 'group': 'system'},
  {'name': 'Kulim Park', 'group': 'system'},
  {'name': 'Kumar One', 'group': 'system'},
  {'name': 'Kumar One Outline', 'group': 'system'},
  {'name': 'Kumbh Sans', 'group': 'system'},
  {'name': 'Kurale', 'group': 'system'},
  {'name': 'La Belle Aurore', 'group': 'system'},
  {'name': 'Lacquer', 'group': 'system'},
  {'name': 'Laila', 'group': 'system'},
  {'name': 'Lakki Reddy', 'group': 'system'},
  {'name': 'Lalezar', 'group': 'system'},
  {'name': 'Lancelot', 'group': 'system'},
  {'name': 'Langar', 'group': 'system'},
  {'name': 'Lateef', 'group': 'system'},
  {'name': 'Lato', 'group': 'system'},
  {'name': 'League Script', 'group': 'system'},
  {'name': 'Leckerli One', 'group': 'system'},
  {'name': 'Ledger', 'group': 'system'},
  {'name': 'Lekton', 'group': 'system'},
  {'name': 'Lemon', 'group': 'system'},
  {'name': 'Lemonada', 'group': 'system'},
  {'name': 'Lexend', 'group': 'system'},
  {'name': 'Lexend Deca', 'group': 'system'},
  {'name': 'Lexend Exa', 'group': 'system'},
  {'name': 'Lexend Giga', 'group': 'system'},
  {'name': 'Lexend Mega', 'group': 'system'},
  {'name': 'Lexend Peta', 'group': 'system'},
  {'name': 'Lexend Tera', 'group': 'system'},
  {'name': 'Lexend Zetta', 'group': 'system'},
  {'name': 'Libre Barcode 128', 'group': 'system'},
  {'name': 'Libre Barcode 128 Text', 'group': 'system'},
  {'name': 'Libre Barcode 39', 'group': 'system'},
  {'name': 'Libre Barcode 39 Extended', 'group': 'system'},
  {'name': 'Libre Barcode 39 Extended Text', 'group': 'system'},
  {'name': 'Libre Barcode 39 Text', 'group': 'system'},
  {'name': 'Libre Baskerville', 'group': 'system'},
  {'name': 'Libre Caslon Display', 'group': 'system'},
  {'name': 'Libre Caslon Text', 'group': 'system'},
  {'name': 'Libre Franklin', 'group': 'system'},
  {'name': 'Life Savers', 'group': 'system'},
  {'name': 'Lilita One', 'group': 'system'},
  {'name': 'Lily Script One', 'group': 'system'},
  {'name': 'Limelight', 'group': 'system'},
  {'name': 'Linden Hill', 'group': 'system'},
  {'name': 'Literata', 'group': 'system'},
  {'name': 'Liu Jian Mao Cao', 'group': 'system'},
  {'name': 'Livvic', 'group': 'system'},
  {'name': 'Lobster', 'group': 'system'},
  {'name': 'Lobster Two', 'group': 'system'},
  {'name': 'Londrina Outline', 'group': 'system'},
  {'name': 'Londrina Shadow', 'group': 'system'},
  {'name': 'Londrina Sketch', 'group': 'system'},
  {'name': 'Londrina Solid', 'group': 'system'},
  {'name': 'Long Cang', 'group': 'system'},
  {'name': 'Lora', 'group': 'system'},
  {'name': 'Love Ya Like A Sister', 'group': 'system'},
  {'name': 'Loved by the King', 'group': 'system'},
  {'name': 'Lovers Quarrel', 'group': 'system'},
  {'name': 'Luckiest Guy', 'group': 'system'},
  {'name': 'Lusitana', 'group': 'system'},
  {'name': 'Lustria', 'group': 'system'},
  {'name': 'Luxurious Script', 'group': 'system'},
  {'name': 'M PLUS 1', 'group': 'system'},
  {'name': 'M PLUS 1 Code', 'group': 'system'},
  {'name': 'M PLUS 1p', 'group': 'system'},
  {'name': 'M PLUS 2', 'group': 'system'},
  {'name': 'M PLUS Code Latin', 'group': 'system'},
  {'name': 'M PLUS Rounded 1c', 'group': 'system'},
  {'name': 'Ma Shan Zheng', 'group': 'system'},
  {'name': 'Macondo', 'group': 'system'},
  {'name': 'Macondo Swash Caps', 'group': 'system'},
  {'name': 'Mada', 'group': 'system'},
  {'name': 'Magra', 'group': 'system'},
  {'name': 'Maiden Orange', 'group': 'system'},
  {'name': 'Maitree', 'group': 'system'},
  {'name': 'Major Mono Display', 'group': 'system'},
  {'name': 'Mako', 'group': 'system'},
  {'name': 'Mali', 'group': 'system'},
  {'name': 'Mallanna', 'group': 'system'},
  {'name': 'Mandali', 'group': 'system'},
  {'name': 'Manjari', 'group': 'system'},
  {'name': 'Manrope', 'group': 'system'},
  {'name': 'Mansalva', 'group': 'system'},
  {'name': 'Manuale', 'group': 'system'},
  {'name': 'Marcellus', 'group': 'system'},
  {'name': 'Marcellus SC', 'group': 'system'},
  {'name': 'Marck Script', 'group': 'system'},
  {'name': 'Margarine', 'group': 'system'},
  {'name': 'Markazi Text', 'group': 'system'},
  {'name': 'Marko One', 'group': 'system'},
  {'name': 'Marmelad', 'group': 'system'},
  {'name': 'Martel', 'group': 'system'},
  {'name': 'Martel Sans', 'group': 'system'},
  {'name': 'Marvel', 'group': 'system'},
  {'name': 'Mate', 'group': 'system'},
  {'name': 'Mate SC', 'group': 'system'},
  {'name': 'Maven Pro', 'group': 'system'},
  {'name': 'McLaren', 'group': 'system'},
  {'name': 'Meddon', 'group': 'system'},
  {'name': 'MedievalSharp', 'group': 'system'},
  {'name': 'Medula One', 'group': 'system'},
  {'name': 'Meera Inimai', 'group': 'system'},
  {'name': 'Megrim', 'group': 'system'},
  {'name': 'Meie Script', 'group': 'system'},
  {'name': 'Meow Script', 'group': 'system'},
  {'name': 'Merienda', 'group': 'system'},
  {'name': 'Merienda One', 'group': 'system'},
  {'name': 'Merriweather', 'group': 'system'},
  {'name': 'Merriweather Sans', 'group': 'system'},
  {'name': 'Metal Mania', 'group': 'system'},
  {'name': 'Metamorphous', 'group': 'system'},
  {'name': 'Metrophobic', 'group': 'system'},
  {'name': 'Michroma', 'group': 'system'},
  {'name': 'Milonga', 'group': 'system'},
  {'name': 'Miltonian', 'group': 'system'},
  {'name': 'Miltonian Tattoo', 'group': 'system'},
  {'name': 'Mina', 'group': 'system'},
  {'name': 'Miniver', 'group': 'system'},
  {'name': 'Miriam Libre', 'group': 'system'},
  {'name': 'Mirza', 'group': 'system'},
  {'name': 'Miss Fajardose', 'group': 'system'},
  {'name': 'Mitr', 'group': 'system'},
  {'name': 'Mochiy Pop One', 'group': 'system'},
  {'name': 'Mochiy Pop P One', 'group': 'system'},
  {'name': 'Modak', 'group': 'system'},
  {'name': 'Modern Antiqua', 'group': 'system'},
  {'name': 'Mogra', 'group': 'system'},
  {'name': 'Mohave', 'group': 'system'},
  {'name': 'Molengo', 'group': 'system'},
  {'name': 'Molle', 'group': 'system'},
  {'name': 'Monda', 'group': 'system'},
  {'name': 'Monofett', 'group': 'system'},
  {'name': 'Monoton', 'group': 'system'},
  {'name': 'Monsieur La Doulaise', 'group': 'system'},
  {'name': 'Montaga', 'group': 'system'},
  {'name': 'Montagu Slab', 'group': 'system'},
  {'name': 'MonteCarlo', 'group': 'system'},
  {'name': 'Montez', 'group': 'system'},
  {'name': 'Montserrat', 'group': 'system'},
  {'name': 'Montserrat Alternates', 'group': 'system'},
  {'name': 'Montserrat Subrayada', 'group': 'system'},
  {'name': 'Mountains of Christmas', 'group': 'system'},
  {'name': 'Mouse Memoirs', 'group': 'system'},
  {'name': 'Mr Bedfort', 'group': 'system'},
  {'name': 'Mr Dafoe', 'group': 'system'},
  {'name': 'Mr De Haviland', 'group': 'system'},
  {'name': 'Mrs Saint Delafield', 'group': 'system'},
  {'name': 'Mrs Sheppards', 'group': 'system'},
  {'name': 'Mukta', 'group': 'system'},
  {'name': 'Mukta Mahee', 'group': 'system'},
  {'name': 'Mukta Malar', 'group': 'system'},
  {'name': 'Mukta Vaani', 'group': 'system'},
  {'name': 'Mulish', 'group': 'system'},
  {'name': 'Murecho', 'group': 'system'},
  {'name': 'MuseoModerno', 'group': 'system'},
  {'name': 'Mystery Quest', 'group': 'system'},
  {'name': 'NTR', 'group': 'system'},
  {'name': 'Nanum Brush Script', 'group': 'system'},
  {'name': 'Nanum Gothic', 'group': 'system'},
  {'name': 'Nanum Gothic Coding', 'group': 'system'},
  {'name': 'Nanum Myeongjo', 'group': 'system'},
  {'name': 'Nanum Pen Script', 'group': 'system'},
  {'name': 'Nerko One', 'group': 'system'},
  {'name': 'Neucha', 'group': 'system'},
  {'name': 'Neuton', 'group': 'system'},
  {'name': 'New Rocker', 'group': 'system'},
  {'name': 'New Tegomin', 'group': 'system'},
  {'name': 'News Cycle', 'group': 'system'},
  {'name': 'Niconne', 'group': 'system'},
  {'name': 'Niramit', 'group': 'system'},
  {'name': 'Nixie One', 'group': 'system'},
  {'name': 'Nobile', 'group': 'system'},
  {'name': 'Norican', 'group': 'system'},
  {'name': 'Nosifer', 'group': 'system'},
  {'name': 'Notable', 'group': 'system'},
  {'name': 'Nothing You Could Do', 'group': 'system'},
  {'name': 'Noticia Text', 'group': 'system'},
  {'name': 'Noto Kufi Arabic', 'group': 'system'},
  {'name': 'Noto Music', 'group': 'system'},
  {'name': 'Noto Naskh Arabic', 'group': 'system'},
  {'name': 'Noto Nastaliq Urdu', 'group': 'system'},
  {'name': 'Noto Rashi Hebrew', 'group': 'system'},
  {'name': 'Noto Sans', 'group': 'system'},
  {'name': 'Noto Sans Adlam', 'group': 'system'},
  {'name': 'Noto Sans Adlam Unjoined', 'group': 'system'},
  {'name': 'Noto Sans Anatolian Hieroglyphs', 'group': 'system'},
  {'name': 'Noto Sans Arabic', 'group': 'system'},
  {'name': 'Noto Sans Armenian', 'group': 'system'},
  {'name': 'Noto Sans Avestan', 'group': 'system'},
  {'name': 'Noto Sans Balinese', 'group': 'system'},
  {'name': 'Noto Sans Bamum', 'group': 'system'},
  {'name': 'Noto Sans Bassa Vah', 'group': 'system'},
  {'name': 'Noto Sans Batak', 'group': 'system'},
  {'name': 'Noto Sans Bengali', 'group': 'system'},
  {'name': 'Noto Sans Bhaiksuki', 'group': 'system'},
  {'name': 'Noto Sans Brahmi', 'group': 'system'},
  {'name': 'Noto Sans Buginese', 'group': 'system'},
  {'name': 'Noto Sans Buhid', 'group': 'system'},
  {'name': 'Noto Sans Canadian Aboriginal', 'group': 'system'},
  {'name': 'Noto Sans Carian', 'group': 'system'},
  {'name': 'Noto Sans Caucasian Albanian', 'group': 'system'},
  {'name': 'Noto Sans Chakma', 'group': 'system'},
  {'name': 'Noto Sans Cham', 'group': 'system'},
  {'name': 'Noto Sans Cherokee', 'group': 'system'},
  {'name': 'Noto Sans Coptic', 'group': 'system'},
  {'name': 'Noto Sans Cuneiform', 'group': 'system'},
  {'name': 'Noto Sans Cypriot', 'group': 'system'},
  {'name': 'Noto Sans Deseret', 'group': 'system'},
  {'name': 'Noto Sans Devanagari', 'group': 'system'},
  {'name': 'Noto Sans Display', 'group': 'system'},
  {'name': 'Noto Sans Duployan', 'group': 'system'},
  {'name': 'Noto Sans Egyptian Hieroglyphs', 'group': 'system'},
  {'name': 'Noto Sans Elbasan', 'group': 'system'},
  {'name': 'Noto Sans Elymaic', 'group': 'system'},
  {'name': 'Noto Sans Georgian', 'group': 'system'},
  {'name': 'Noto Sans Glagolitic', 'group': 'system'},
  {'name': 'Noto Sans Gothic', 'group': 'system'},
  {'name': 'Noto Sans Grantha', 'group': 'system'},
  {'name': 'Noto Sans Gujarati', 'group': 'system'},
  {'name': 'Noto Sans Gunjala Gondi', 'group': 'system'},
  {'name': 'Noto Sans Gurmukhi', 'group': 'system'},
  {'name': 'Noto Sans Hanifi Rohingya', 'group': 'system'},
  {'name': 'Noto Sans Hanunoo', 'group': 'system'},
  {'name': 'Noto Sans Hatran', 'group': 'system'},
  {'name': 'Noto Sans Hebrew', 'group': 'system'},
  {'name': 'Noto Sans Imperial Aramaic', 'group': 'system'},
  {'name': 'Noto Sans Indic Siyaq Numbers', 'group': 'system'},
  {'name': 'Noto Sans Inscriptional Pahlavi', 'group': 'system'},
  {'name': 'Noto Sans Inscriptional Parthian', 'group': 'system'},
  {'name': 'Noto Sans Javanese', 'group': 'system'},
  {'name': 'Noto Sans Kaithi', 'group': 'system'},
  {'name': 'Noto Sans Kannada', 'group': 'system'},
  {'name': 'Noto Sans Kayah Li', 'group': 'system'},
  {'name': 'Noto Sans Kharoshthi', 'group': 'system'},
  {'name': 'Noto Sans Khmer', 'group': 'system'},
  {'name': 'Noto Sans Khojki', 'group': 'system'},
  {'name': 'Noto Sans Khudawadi', 'group': 'system'},
  {'name': 'Noto Sans Lao', 'group': 'system'},
  {'name': 'Noto Sans Lepcha', 'group': 'system'},
  {'name': 'Noto Sans Limbu', 'group': 'system'},
  {'name': 'Noto Sans Linear A', 'group': 'system'},
  {'name': 'Noto Sans Linear B', 'group': 'system'},
  {'name': 'Noto Sans Lisu', 'group': 'system'},
  {'name': 'Noto Sans Lycian', 'group': 'system'},
  {'name': 'Noto Sans Lydian', 'group': 'system'},
  {'name': 'Noto Sans Mahajani', 'group': 'system'},
  {'name': 'Noto Sans Malayalam', 'group': 'system'},
  {'name': 'Noto Sans Mandaic', 'group': 'system'},
  {'name': 'Noto Sans Manichaean', 'group': 'system'},
  {'name': 'Noto Sans Marchen', 'group': 'system'},
  {'name': 'Noto Sans Masaram Gondi', 'group': 'system'},
  {'name': 'Noto Sans Math', 'group': 'system'},
  {'name': 'Noto Sans Mayan Numerals', 'group': 'system'},
  {'name': 'Noto Sans Medefaidrin', 'group': 'system'},
  {'name': 'Noto Sans Meetei Mayek', 'group': 'system'},
  {'name': 'Noto Sans Meroitic', 'group': 'system'},
  {'name': 'Noto Sans Miao', 'group': 'system'},
  {'name': 'Noto Sans Modi', 'group': 'system'},
  {'name': 'Noto Sans Mongolian', 'group': 'system'},
  {'name': 'Noto Sans Mono', 'group': 'system'},
  {'name': 'Noto Sans Mro', 'group': 'system'},
  {'name': 'Noto Sans Multani', 'group': 'system'},
  {'name': 'Noto Sans Myanmar', 'group': 'system'},
  {'name': 'Noto Sans N Ko', 'group': 'system'},
  {'name': 'Noto Sans Nabataean', 'group': 'system'},
  {'name': 'Noto Sans New Tai Lue', 'group': 'system'},
  {'name': 'Noto Sans Newa', 'group': 'system'},
  {'name': 'Noto Sans Nushu', 'group': 'system'},
  {'name': 'Noto Sans Ogham', 'group': 'system'},
  {'name': 'Noto Sans Ol Chiki', 'group': 'system'},
  {'name': 'Noto Sans Old Hungarian', 'group': 'system'},
  {'name': 'Noto Sans Old Italic', 'group': 'system'},
  {'name': 'Noto Sans Old North Arabian', 'group': 'system'},
  {'name': 'Noto Sans Old Permic', 'group': 'system'},
  {'name': 'Noto Sans Old Persian', 'group': 'system'},
  {'name': 'Noto Sans Old Sogdian', 'group': 'system'},
  {'name': 'Noto Sans Old South Arabian', 'group': 'system'},
  {'name': 'Noto Sans Old Turkic', 'group': 'system'},
  {'name': 'Noto Sans Oriya', 'group': 'system'},
  {'name': 'Noto Sans Osage', 'group': 'system'},
  {'name': 'Noto Sans Osmanya', 'group': 'system'},
  {'name': 'Noto Sans Pahawh Hmong', 'group': 'system'},
  {'name': 'Noto Sans Palmyrene', 'group': 'system'},
  {'name': 'Noto Sans Pau Cin Hau', 'group': 'system'},
  {'name': 'Noto Sans Phags Pa', 'group': 'system'},
  {'name': 'Noto Sans Phoenician', 'group': 'system'},
  {'name': 'Noto Sans Psalter Pahlavi', 'group': 'system'},
  {'name': 'Noto Sans Rejang', 'group': 'system'},
  {'name': 'Noto Sans Runic', 'group': 'system'},
  {'name': 'Noto Sans Samaritan', 'group': 'system'},
  {'name': 'Noto Sans Saurashtra', 'group': 'system'},
  {'name': 'Noto Sans Sharada', 'group': 'system'},
  {'name': 'Noto Sans Shavian', 'group': 'system'},
  {'name': 'Noto Sans Siddham', 'group': 'system'},
  {'name': 'Noto Sans Sinhala', 'group': 'system'},
  {'name': 'Noto Sans Sogdian', 'group': 'system'},
  {'name': 'Noto Sans Sora Sompeng', 'group': 'system'},
  {'name': 'Noto Sans Soyombo', 'group': 'system'},
  {'name': 'Noto Sans Sundanese', 'group': 'system'},
  {'name': 'Noto Sans Syloti Nagri', 'group': 'system'},
  {'name': 'Noto Sans Symbols', 'group': 'system'},
  {'name': 'Noto Sans Symbols 2', 'group': 'system'},
  {'name': 'Noto Sans Syriac', 'group': 'system'},
  {'name': 'Noto Sans Tagalog', 'group': 'system'},
  {'name': 'Noto Sans Tagbanwa', 'group': 'system'},
  {'name': 'Noto Sans Tai Le', 'group': 'system'},
  {'name': 'Noto Sans Tai Tham', 'group': 'system'},
  {'name': 'Noto Sans Tai Viet', 'group': 'system'},
  {'name': 'Noto Sans Takri', 'group': 'system'},
  {'name': 'Noto Sans Tamil', 'group': 'system'},
  {'name': 'Noto Sans Tamil Supplement', 'group': 'system'},
  {'name': 'Noto Sans Telugu', 'group': 'system'},
  {'name': 'Noto Sans Thaana', 'group': 'system'},
  {'name': 'Noto Sans Thai', 'group': 'system'},
  {'name': 'Noto Sans Thai Looped', 'group': 'system'},
  {'name': 'Noto Sans Tifinagh', 'group': 'system'},
  {'name': 'Noto Sans Tirhuta', 'group': 'system'},
  {'name': 'Noto Sans Ugaritic', 'group': 'system'},
  {'name': 'Noto Sans Vai', 'group': 'system'},
  {'name': 'Noto Sans Wancho', 'group': 'system'},
  {'name': 'Noto Sans Warang Citi', 'group': 'system'},
  {'name': 'Noto Sans Yi', 'group': 'system'},
  {'name': 'Noto Sans Zanabazar Square', 'group': 'system'},
  {'name': 'Noto Serif', 'group': 'system'},
  {'name': 'Noto Serif Ahom', 'group': 'system'},
  {'name': 'Noto Serif Armenian', 'group': 'system'},
  {'name': 'Noto Serif Balinese', 'group': 'system'},
  {'name': 'Noto Serif Bengali', 'group': 'system'},
  {'name': 'Noto Serif Devanagari', 'group': 'system'},
  {'name': 'Noto Serif Display', 'group': 'system'},
  {'name': 'Noto Serif Dogra', 'group': 'system'},
  {'name': 'Noto Serif Ethiopic', 'group': 'system'},
  {'name': 'Noto Serif Georgian', 'group': 'system'},
  {'name': 'Noto Serif Grantha', 'group': 'system'},
  {'name': 'Noto Serif Gujarati', 'group': 'system'},
  {'name': 'Noto Serif Gurmukhi', 'group': 'system'},
  {'name': 'Noto Serif Hebrew', 'group': 'system'},
  {'name': 'Noto Serif Kannada', 'group': 'system'},
  {'name': 'Noto Serif Khmer', 'group': 'system'},
  {'name': 'Noto Serif Lao', 'group': 'system'},
  {'name': 'Noto Serif Malayalam', 'group': 'system'},
  {'name': 'Noto Serif Myanmar', 'group': 'system'},
  {'name': 'Noto Serif Nyiakeng Puachue Hmong', 'group': 'system'},
  {'name': 'Noto Serif Sinhala', 'group': 'system'},
  {'name': 'Noto Serif Tamil', 'group': 'system'},
  {'name': 'Noto Serif Tangut', 'group': 'system'},
  {'name': 'Noto Serif Telugu', 'group': 'system'},
  {'name': 'Noto Serif Thai', 'group': 'system'},
  {'name': 'Noto Serif Tibetan', 'group': 'system'},
  {'name': 'Noto Serif Yezidi', 'group': 'system'},
  {'name': 'Noto Traditional Nushu', 'group': 'system'},
  {'name': 'Nova Cut', 'group': 'system'},
  {'name': 'Nova Flat', 'group': 'system'},
  {'name': 'Nova Mono', 'group': 'system'},
  {'name': 'Nova Oval', 'group': 'system'},
  {'name': 'Nova Round', 'group': 'system'},
  {'name': 'Nova Script', 'group': 'system'},
  {'name': 'Nova Slim', 'group': 'system'},
  {'name': 'Nova Square', 'group': 'system'},
  {'name': 'Numans', 'group': 'system'},
  {'name': 'Nunito', 'group': 'system'},
  {'name': 'Nunito Sans', 'group': 'system'},
  {'name': 'Odibee Sans', 'group': 'system'},
  {'name': 'Odor Mean Chey', 'group': 'system'},
  {'name': 'Offside', 'group': 'system'},
  {'name': 'Oi', 'group': 'system'},
  {'name': 'Old Standard TT', 'group': 'system'},
  {'name': 'Oldenburg', 'group': 'system'},
  {'name': 'Oleo Script', 'group': 'system'},
  {'name': 'Oleo Script Swash Caps', 'group': 'system'},
  {'name': 'Open Sans', 'group': 'system'},
  {'name': 'Open Sans Condensed', 'group': 'system'},
  {'name': 'Oranienbaum', 'group': 'system'},
  {'name': 'Orbitron', 'group': 'system'},
  {'name': 'Oregano', 'group': 'system'},
  {'name': 'Orienta', 'group': 'system'},
  {'name': 'Original Surfer', 'group': 'system'},
  {'name': 'Oswald', 'group': 'system'},
  {'name': 'Otomanopee One', 'group': 'system'},
  {'name': 'Outfit', 'group': 'system'},
  {'name': 'Over the Rainbow', 'group': 'system'},
  {'name': 'Overlock', 'group': 'system'},
  {'name': 'Overlock SC', 'group': 'system'},
  {'name': 'Overpass', 'group': 'system'},
  {'name': 'Overpass Mono', 'group': 'system'},
  {'name': 'Ovo', 'group': 'system'},
  {'name': 'Oxanium', 'group': 'system'},
  {'name': 'Oxygen', 'group': 'system'},
  {'name': 'Oxygen Mono', 'group': 'system'},
  {'name': 'PT Mono', 'group': 'system'},
  {'name': 'PT Sans', 'group': 'system'},
  {'name': 'PT Sans Caption', 'group': 'system'},
  {'name': 'PT Sans Narrow', 'group': 'system'},
  {'name': 'PT Serif', 'group': 'system'},
  {'name': 'PT Serif Caption', 'group': 'system'},
  {'name': 'Pacifico', 'group': 'system'},
  {'name': 'Padauk', 'group': 'system'},
  {'name': 'Palanquin', 'group': 'system'},
  {'name': 'Palanquin Dark', 'group': 'system'},
  {'name': 'Palette Mosaic', 'group': 'system'},
  {'name': 'Pangolin', 'group': 'system'},
  {'name': 'Paprika', 'group': 'system'},
  {'name': 'Parisienne', 'group': 'system'},
  {'name': 'Passero One', 'group': 'system'},
  {'name': 'Passion One', 'group': 'system'},
  {'name': 'Passions Conflict', 'group': 'system'},
  {'name': 'Pathway Gothic One', 'group': 'system'},
  {'name': 'Patrick Hand', 'group': 'system'},
  {'name': 'Patrick Hand SC', 'group': 'system'},
  {'name': 'Pattaya', 'group': 'system'},
  {'name': 'Patua One', 'group': 'system'},
  {'name': 'Pavanam', 'group': 'system'},
  {'name': 'Paytone One', 'group': 'system'},
  {'name': 'Peddana', 'group': 'system'},
  {'name': 'Peralta', 'group': 'system'},
  {'name': 'Permanent Marker', 'group': 'system'},
  {'name': 'Petemoss', 'group': 'system'},
  {'name': 'Petit Formal Script', 'group': 'system'},
  {'name': 'Petrona', 'group': 'system'},
  {'name': 'Philosopher', 'group': 'system'},
  {'name': 'Piazzolla', 'group': 'system'},
  {'name': 'Piedra', 'group': 'system'},
  {'name': 'Pinyon Script', 'group': 'system'},
  {'name': 'Pirata One', 'group': 'system'},
  {'name': 'Plaster', 'group': 'system'},
  {'name': 'Play', 'group': 'system'},
  {'name': 'Playball', 'group': 'system'},
  {'name': 'Playfair Display', 'group': 'system'},
  {'name': 'Playfair Display SC', 'group': 'system'},
  {'name': 'Podkova', 'group': 'system'},
  {'name': 'Poiret One', 'group': 'system'},
  {'name': 'Poller One', 'group': 'system'},
  {'name': 'Poly', 'group': 'system'},
  {'name': 'Pompiere', 'group': 'system'},
  {'name': 'Pontano Sans', 'group': 'system'},
  {'name': 'Poor Story', 'group': 'system'},
  {'name': 'Poppins', 'group': 'system'},
  {'name': 'Port Lligat Sans', 'group': 'system'},
  {'name': 'Port Lligat Slab', 'group': 'system'},
  {'name': 'Potta One', 'group': 'system'},
  {'name': 'Pragati Narrow', 'group': 'system'},
  {'name': 'Praise', 'group': 'system'},
  {'name': 'Prata', 'group': 'system'},
  {'name': 'Press Start 2P', 'group': 'system'},
  {'name': 'Pridi', 'group': 'system'},
  {'name': 'Princess Sofia', 'group': 'system'},
  {'name': 'Prociono', 'group': 'system'},
  {'name': 'Prompt', 'group': 'system'},
  {'name': 'Prosto One', 'group': 'system'},
  {'name': 'Proza Libre', 'group': 'system'},
  {'name': 'Public Sans', 'group': 'system'},
  {'name': 'Puppies Play', 'group': 'system'},
  {'name': 'Puritan', 'group': 'system'},
  {'name': 'Purple Purse', 'group': 'system'},
  {'name': 'Qahiri', 'group': 'system'},
  {'name': 'Quando', 'group': 'system'},
  {'name': 'Quantico', 'group': 'system'},
  {'name': 'Quattrocento', 'group': 'system'},
  {'name': 'Quattrocento Sans', 'group': 'system'},
  {'name': 'Questrial', 'group': 'system'},
  {'name': 'Quicksand', 'group': 'system'},
  {'name': 'Quintessential', 'group': 'system'},
  {'name': 'Qwigley', 'group': 'system'},
  {'name': 'Racing Sans One', 'group': 'system'},
  {'name': 'Radley', 'group': 'system'},
  {'name': 'Rajdhani', 'group': 'system'},
  {'name': 'Rakkas', 'group': 'system'},
  {'name': 'Raleway', 'group': 'system'},
  {'name': 'Raleway Dots', 'group': 'system'},
  {'name': 'Ramabhadra', 'group': 'system'},
  {'name': 'Ramaraja', 'group': 'system'},
  {'name': 'Rambla', 'group': 'system'},
  {'name': 'Rammetto One', 'group': 'system'},
  {'name': 'Rampart One', 'group': 'system'},
  {'name': 'Ranchers', 'group': 'system'},
  {'name': 'Rancho', 'group': 'system'},
  {'name': 'Ranga', 'group': 'system'},
  {'name': 'Rasa', 'group': 'system'},
  {'name': 'Rationale', 'group': 'system'},
  {'name': 'Ravi Prakash', 'group': 'system'},
  {'name': 'Readex Pro', 'group': 'system'},
  {'name': 'Recursive', 'group': 'system'},
  {'name': 'Red Hat Display', 'group': 'system'},
  {'name': 'Red Hat Mono', 'group': 'system'},
  {'name': 'Red Hat Text', 'group': 'system'},
  {'name': 'Red Rose', 'group': 'system'},
  {'name': 'Redacted', 'group': 'system'},
  {'name': 'Redacted Script', 'group': 'system'},
  {'name': 'Redressed', 'group': 'system'},
  {'name': 'Reem Kufi', 'group': 'system'},
  {'name': 'Reenie Beanie', 'group': 'system'},
  {'name': 'Reggae One', 'group': 'system'},
  {'name': 'Revalia', 'group': 'system'},
  {'name': 'Rhodium Libre', 'group': 'system'},
  {'name': 'Ribeye', 'group': 'system'},
  {'name': 'Ribeye Marrow', 'group': 'system'},
  {'name': 'Righteous', 'group': 'system'},
  {'name': 'Risque', 'group': 'system'},
  {'name': 'Road Rage', 'group': 'system'},
  {'name': 'Roboto', 'group': 'system'},
  {'name': 'Roboto Condensed', 'group': 'system'},
  {'name': 'Roboto Mono', 'group': 'system'},
  {'name': 'Roboto Slab', 'group': 'system'},
  {'name': 'Rochester', 'group': 'system'},
  {'name': 'Rock 3D', 'group': 'system'},
  {'name': 'Rock Salt', 'group': 'system'},
  {'name': 'RocknRoll One', 'group': 'system'},
  {'name': 'Rokkitt', 'group': 'system'},
  {'name': 'Romanesco', 'group': 'system'},
  {'name': 'Ropa Sans', 'group': 'system'},
  {'name': 'Rosario', 'group': 'system'},
  {'name': 'Rosarivo', 'group': 'system'},
  {'name': 'Rouge Script', 'group': 'system'},
  {'name': 'Rowdies', 'group': 'system'},
  {'name': 'Rozha One', 'group': 'system'},
  {'name': 'Rubik', 'group': 'system'},
  {'name': 'Rubik Beastly', 'group': 'system'},
  {'name': 'Rubik Mono One', 'group': 'system'},
  {'name': 'Ruda', 'group': 'system'},
  {'name': 'Rufina', 'group': 'system'},
  {'name': 'Ruge Boogie', 'group': 'system'},
  {'name': 'Ruluko', 'group': 'system'},
  {'name': 'Rum Raisin', 'group': 'system'},
  {'name': 'Ruslan Display', 'group': 'system'},
  {'name': 'Russo One', 'group': 'system'},
  {'name': 'Ruthie', 'group': 'system'},
  {'name': 'Rye', 'group': 'system'},
  {'name': 'STIX Two Text', 'group': 'system'},
  {'name': 'Sacramento', 'group': 'system'},
  {'name': 'Sahitya', 'group': 'system'},
  {'name': 'Sail', 'group': 'system'},
  {'name': 'Saira', 'group': 'system'},
  {'name': 'Saira Condensed', 'group': 'system'},
  {'name': 'Saira Extra Condensed', 'group': 'system'},
  {'name': 'Saira Semi Condensed', 'group': 'system'},
  {'name': 'Saira Stencil One', 'group': 'system'},
  {'name': 'Salsa', 'group': 'system'},
  {'name': 'Sanchez', 'group': 'system'},
  {'name': 'Sancreek', 'group': 'system'},
  {'name': 'Sansita', 'group': 'system'},
  {'name': 'Sansita Swashed', 'group': 'system'},
  {'name': 'Sarabun', 'group': 'system'},
  {'name': 'Sarala', 'group': 'system'},
  {'name': 'Sarina', 'group': 'system'},
  {'name': 'Sarpanch', 'group': 'system'},
  {'name': 'Sassy Frass', 'group': 'system'},
  {'name': 'Satisfy', 'group': 'system'},
  {'name': 'Sawarabi Gothic', 'group': 'system'},
  {'name': 'Sawarabi Mincho', 'group': 'system'},
  {'name': 'Scada', 'group': 'system'},
  {'name': 'Scheherazade New', 'group': 'system'},
  {'name': 'Schoolbell', 'group': 'system'},
  {'name': 'Scope One', 'group': 'system'},
  {'name': 'Seaweed Script', 'group': 'system'},
  {'name': 'Secular One', 'group': 'system'},
  {'name': 'Sedgwick Ave', 'group': 'system'},
  {'name': 'Sedgwick Ave Display', 'group': 'system'},
  {'name': 'Sen', 'group': 'system'},
  {'name': 'Sevillana', 'group': 'system'},
  {'name': 'Seymour One', 'group': 'system'},
  {'name': 'Shadows Into Light', 'group': 'system'},
  {'name': 'Shadows Into Light Two', 'group': 'system'},
  {'name': 'Shalimar', 'group': 'system'},
  {'name': 'Shanti', 'group': 'system'},
  {'name': 'Share', 'group': 'system'},
  {'name': 'Share Tech', 'group': 'system'},
  {'name': 'Share Tech Mono', 'group': 'system'},
  {'name': 'Shippori Antique', 'group': 'system'},
  {'name': 'Shippori Antique B1', 'group': 'system'},
  {'name': 'Shippori Mincho', 'group': 'system'},
  {'name': 'Shippori Mincho B1', 'group': 'system'},
  {'name': 'Shizuru', 'group': 'system'},
  {'name': 'Shojumaru', 'group': 'system'},
  {'name': 'Short Stack', 'group': 'system'},
  {'name': 'Shrikhand', 'group': 'system'},
  {'name': 'Sigmar One', 'group': 'system'},
  {'name': 'Signika', 'group': 'system'},
  {'name': 'Signika Negative', 'group': 'system'},
  {'name': 'Simonetta', 'group': 'system'},
  {'name': 'Single Day', 'group': 'system'},
  {'name': 'Sintony', 'group': 'system'},
  {'name': 'Sirin Stencil', 'group': 'system'},
  {'name': 'Six Caps', 'group': 'system'},
  {'name': 'Skranji', 'group': 'system'},
  {'name': 'Slabo 13px', 'group': 'system'},
  {'name': 'Slabo 27px', 'group': 'system'},
  {'name': 'Slackey', 'group': 'system'},
  {'name': 'Smokum', 'group': 'system'},
  {'name': 'Smooch', 'group': 'system'},
  {'name': 'Smythe', 'group': 'system'},
  {'name': 'Sniglet', 'group': 'system'},
  {'name': 'Snippet', 'group': 'system'},
  {'name': 'Snowburst One', 'group': 'system'},
  {'name': 'Sofadi One', 'group': 'system'},
  {'name': 'Sofia', 'group': 'system'},
  {'name': 'Solway', 'group': 'system'},
  {'name': 'Song Myung', 'group': 'system'},
  {'name': 'Sonsie One', 'group': 'system'},
  {'name': 'Sora', 'group': 'system'},
  {'name': 'Sorts Mill Goudy', 'group': 'system'},
  {'name': 'Source Code Pro', 'group': 'system'},
  {'name': 'Source Sans 3', 'group': 'system'},
  {'name': 'Source Sans Pro', 'group': 'system'},
  {'name': 'Source Serif Pro', 'group': 'system'},
  {'name': 'Space Grotesk', 'group': 'system'},
  {'name': 'Space Mono', 'group': 'system'},
  {'name': 'Special Elite', 'group': 'system'},
  {'name': 'Spectral', 'group': 'system'},
  {'name': 'Spectral SC', 'group': 'system'},
  {'name': 'Spicy Rice', 'group': 'system'},
  {'name': 'Spinnaker', 'group': 'system'},
  {'name': 'Spirax', 'group': 'system'},
  {'name': 'Squada One', 'group': 'system'},
  {'name': 'Sree Krushnadevaraya', 'group': 'system'},
  {'name': 'Sriracha', 'group': 'system'},
  {'name': 'Srisakdi', 'group': 'system'},
  {'name': 'Staatliches', 'group': 'system'},
  {'name': 'Stalemate', 'group': 'system'},
  {'name': 'Stalinist One', 'group': 'system'},
  {'name': 'Stardos Stencil', 'group': 'system'},
  {'name': 'Stick', 'group': 'system'},
  {'name': 'Stick No Bills', 'group': 'system'},
  {'name': 'Stint Ultra Condensed', 'group': 'system'},
  {'name': 'Stint Ultra Expanded', 'group': 'system'},
  {'name': 'Stoke', 'group': 'system'},
  {'name': 'Strait', 'group': 'system'},
  {'name': 'Style Script', 'group': 'system'},
  {'name': 'Stylish', 'group': 'system'},
  {'name': 'Sue Ellen Francisco', 'group': 'system'},
  {'name': 'Suez One', 'group': 'system'},
  {'name': 'Sulphur Point', 'group': 'system'},
  {'name': 'Sumana', 'group': 'system'},
  {'name': 'Sunflower', 'group': 'system'},
  {'name': 'Sunshiney', 'group': 'system'},
  {'name': 'Supermercado One', 'group': 'system'},
  {'name': 'Sura', 'group': 'system'},
  {'name': 'Suranna', 'group': 'system'},
  {'name': 'Suravaram', 'group': 'system'},
  {'name': 'Swanky and Moo Moo', 'group': 'system'},
  {'name': 'Syncopate', 'group': 'system'},
  {'name': 'Syne', 'group': 'system'},
  {'name': 'Syne Mono', 'group': 'system'},
  {'name': 'Syne Tactile', 'group': 'system'},
  {'name': 'Tajawal', 'group': 'system'},
  {'name': 'Tangerine', 'group': 'system'},
  {'name': 'Tauri', 'group': 'system'},
  {'name': 'Taviraj', 'group': 'system'},
  {'name': 'Teko', 'group': 'system'},
  {'name': 'Telex', 'group': 'system'},
  {'name': 'Tenali Ramakrishna', 'group': 'system'},
  {'name': 'Tenor Sans', 'group': 'system'},
  {'name': 'Text Me One', 'group': 'system'},
  {'name': 'Thasadith', 'group': 'system'},
  {'name': 'The Girl Next Door', 'group': 'system'},
  {'name': 'Tienne', 'group': 'system'},
  {'name': 'Tillana', 'group': 'system'},
  {'name': 'Timmana', 'group': 'system'},
  {'name': 'Tinos', 'group': 'system'},
  {'name': 'Titan One', 'group': 'system'},
  {'name': 'Titillium Web', 'group': 'system'},
  {'name': 'Tomorrow', 'group': 'system'},
  {'name': 'Tourney', 'group': 'system'},
  {'name': 'Trade Winds', 'group': 'system'},
  {'name': 'Train One', 'group': 'system'},
  {'name': 'Trirong', 'group': 'system'},
  {'name': 'Trispace', 'group': 'system'},
  {'name': 'Trocchi', 'group': 'system'},
  {'name': 'Trochut', 'group': 'system'},
  {'name': 'Trykker', 'group': 'system'},
  {'name': 'Tulpen One', 'group': 'system'},
  {'name': 'Turret Road', 'group': 'system'},
  {'name': 'Ubuntu', 'group': 'system'},
  {'name': 'Ubuntu Condensed', 'group': 'system'},
  {'name': 'Ubuntu Mono', 'group': 'system'},
  {'name': 'Uchen', 'group': 'system'},
  {'name': 'Ultra', 'group': 'system'},
  {'name': 'Uncial Antiqua', 'group': 'system'},
  {'name': 'Underdog', 'group': 'system'},
  {'name': 'Unica One', 'group': 'system'},
  {'name': 'UnifrakturCook', 'group': 'system'},
  {'name': 'UnifrakturMaguntia', 'group': 'system'},
  {'name': 'Unkempt', 'group': 'system'},
  {'name': 'Unlock', 'group': 'system'},
  {'name': 'Unna', 'group': 'system'},
  {'name': 'Urbanist', 'group': 'system'},
  {'name': 'VT323', 'group': 'system'},
  {'name': 'Vampiro One', 'group': 'system'},
  {'name': 'Varela', 'group': 'system'},
  {'name': 'Varela Round', 'group': 'system'},
  {'name': 'Varta', 'group': 'system'},
  {'name': 'Vast Shadow', 'group': 'system'},
  {'name': 'Vesper Libre', 'group': 'system'},
  {'name': 'Viaoda Libre', 'group': 'system'},
  {'name': 'Vibes', 'group': 'system'},
  {'name': 'Vibur', 'group': 'system'},
  {'name': 'Vidaloka', 'group': 'system'},
  {'name': 'Viga', 'group': 'system'},
  {'name': 'Voces', 'group': 'system'},
  {'name': 'Volkhov', 'group': 'system'},
  {'name': 'Vollkorn', 'group': 'system'},
  {'name': 'Vollkorn SC', 'group': 'system'},
  {'name': 'Voltaire', 'group': 'system'},
  {'name': 'Waiting for the Sunrise', 'group': 'system'},
  {'name': 'Wallpoet', 'group': 'system'},
  {'name': 'Walter Turncoat', 'group': 'system'},
  {'name': 'Warnes', 'group': 'system'},
  {'name': 'Wellfleet', 'group': 'system'},
  {'name': 'Wendy One', 'group': 'system'},
  {'name': 'WindSong', 'group': 'system'},
  {'name': 'Wire One', 'group': 'system'},
  {'name': 'Work Sans', 'group': 'system'},
  {'name': 'Xanh Mono', 'group': 'system'},
  {'name': 'Yaldevi', 'group': 'system'},
  {'name': 'Yanone Kaffeesatz', 'group': 'system'},
  {'name': 'Yantramanav', 'group': 'system'},
  {'name': 'Yatra One', 'group': 'system'},
  {'name': 'Yellowtail', 'group': 'system'},
  {'name': 'Yeon Sung', 'group': 'system'},
  {'name': 'Yeseva One', 'group': 'system'},
  {'name': 'Yesteryear', 'group': 'system'},
  {'name': 'Yomogi', 'group': 'system'},
  {'name': 'Yrsa', 'group': 'system'},
  {'name': 'Yuji Boku', 'group': 'system'},
  {'name': 'Yuji Hentaigana Akari', 'group': 'system'},
  {'name': 'Yuji Hentaigana Akebono', 'group': 'system'},
  {'name': 'Yuji Mai', 'group': 'system'},
  {'name': 'Yuji Syuku', 'group': 'system'},
  {'name': 'Yusei Magic', 'group': 'system'},
  {'name': 'ZCOOL KuaiLe', 'group': 'system'},
  {'name': 'ZCOOL QingKe HuangYou', 'group': 'system'},
  {'name': 'ZCOOL XiaoWei', 'group': 'system'},
  {'name': 'Zen Antique', 'group': 'system'},
  {'name': 'Zen Antique Soft', 'group': 'system'},
  {'name': 'Zen Kaku Gothic Antique', 'group': 'system'},
  {'name': 'Zen Kaku Gothic New', 'group': 'system'},
  {'name': 'Zen Kurenaido', 'group': 'system'},
  {'name': 'Zen Loop', 'group': 'system'},
  {'name': 'Zen Maru Gothic', 'group': 'system'},
  {'name': 'Zen Old Mincho', 'group': 'system'},
  {'name': 'Zen Tokyo Zoo', 'group': 'system'},
  {'name': 'Zeyada', 'group': 'system'},
  {'name': 'Zhi Mang Xing', 'group': 'system'},
  {'name': 'Zilla Slab', 'group': 'system'},
  {'name': 'Zilla Slab Highlight', 'group': 'system'},
];
